### ISSUE TITLE
Foils not being correctly identified

### ISSUE THREAD

**Issue by nikkopt** [demogorgon1/mkmcsv#14]
The program is identifying most cards on the csv as being foils when they are not.

csv from cardmarket:
```
idProduct;groupCount;price;idLanguage;condition;isFoil;isSigned;isAltered;isPlayset;isReverseHolo;isFirstEd;isFullArt;isUberRare;isWithDie
3007;1;0.02;8;2;;;;;;;;;
19824;1;0.02;1;2;;;;;;;;;
20749;1;0.02;1;2;;;;;;;;
```

csv generated from mkmcsv:

```
name                                     |set_name                                   |condition|foil |promo|price|cardmarket_id|
-----------------------------------------|-------------------------------------------|---------|-----|-----|-----|-------------|
                                      Fog|                            Seventh Edition|        2| true|false| 0.02|         3007|
                          Resounding Wave|                            Shards of Alara|        2| true|false| 0.02|        19824|
                        Exploding Borders|                                    Conflux|        2| true|false| 0.02|        20749|
```

![Capturar](https://user-images.githubusercontent.com/2060960/188451689-291ece12-b44e-4c1c-a874-8dcfde0e520a.PNG)

**Comment by demogorgon1** [comment]
Definitely a bug, thanks again. I've only really used this with '93-'94 cards, so haven't tested it properly with foils (or non-english cards). I'll look into it.

**Comment by nikkopt** [comment]
[ArticlesFromShipment.csv](https://github.com/demogorgon1/mkmcsv/files/9509079/ArticlesFromShipment.csv)
Here, maybe it can help you test.

**Comment by demogorgon1** [comment]
It wasn't really a bug. The "foil" column is scryfall saying whether the card is available as a foil or not. Similarily "nonfoil" indicates if there is a non-foil one available.
The column you need is "is_foil". Not very intuitive, I know. :)

**Comment by nikkopt** [comment]
Doh! Sorry about that. Thanks.
