### ISSUE TITLE
(Improvement) Give the option to export condition as text

### ISSUE THREAD

**Issue by nikkopt** [demogorgon1/mkmcsv#15]
Not really critical as this can be done in a spreadsheet pretty easily, but it would be nice if we could export the condition values as text, as they are described in CardMarket [here](https://www.cardmarket.com/en/Magic/Help/CardCondition) . I tried importing the converted csv file into deckstats.net and it doesn't know what to do the the values as numbers. I guess other apps and websites will also struggle. 
Deckstats.net also accepts the condition as 2 letters (NM,LP,GD, etc) and i think most websites and apps do too.
Another thing that would be nice is if you could also give the option to output the condition in the format the US uses, doing the conversion in the process. For example, if i try to upload the csv file into deckbox.org with cards with "Excellent" as the condition, it won't accept because they don't use it. You can read about it [here](https://thecardcollective.com/en-us/pages/condition-guide)

**Comment by demogorgon1** [comment]
Added a new column type "condition_string" with the cardmarket condition as text (two-letter code). Keeping the issue open because didn't add US condition support.
EDIT: Added a "condition_string_us" column.

**Comment by nikkopt** [comment]
You're the man

**Comment by nikkopt** [comment]
I just tried exporting with the csv_language column and it also exports numbers. Rahhh, i should have seen this earlier. using "language" seems to fetch it from scryfall and puts "en" in every card.
The only place i can find the values of those numbers is [here](https://gist.github.com/n21lv/ca7dbefd5955afc7205049ad950aec96)

```
 const langDB = {
            1: 'English',
            2: 'French',
            3: 'German',
            4: 'Spanish',
            5: 'Italian',
            6: 'Simplified Chinese',
            7: 'Japanese',
            8: 'Portuguese',
            9: 'Russian',
            10: 'Korean',
            11: 'Traditional Chinese'
```

Should i open another issue? I feel like i'm making you my slave and that's not my intention at all. I can easily change the values on excel. Just trying to think of other users

**Comment by demogorgon1** [comment]
No problemo, I appreciate you making these suggestions. You already did most of the work. :) I'll add a "language_name" column, shouldn't take much effort.

**Comment by demogorgon1** [comment]
Yeah, it seems like scryfall simply isn't providing separate cardmarket ids for non-english cards (although for some old cards it seems to work as intended... not very consistent unfortunately).
Scryfall is basically returning data for the wrong card, so image URLs and pricing info will be for the english version as well (I assume, can't really test it now).
Easy workaround, like you suggest, is to just rely on the language from the original CSV file. Will add a text verson of that.
Will also look into getting the correct card as it should basically just make another scryfall request when it realizes there is a mismatch. It's a bit more work tho, gonna make an issue for that and look into it Eventually (tm).
